# Generated by Django 5.2.17 on 2026-09-04 09:09

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address_alter_user_email_and_more'),
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('flat_rate_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('free_over_toman', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('delivery_min_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivery_max_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('finalization_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ready', 'Ready for order'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=16)),
                ('cart_revision', models.PositiveBigIntegerField()),
                ('subtotal_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('discount_toman', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('shipping_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('tax_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('payable_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('tax_rate_bps', models.PositiveSmallIntegerField()),
                ('address_snapshot', models.JSONField()),
                ('shipping_snapshot', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='accounts.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='checkout.shippingmethod')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CheckoutTaxPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('rate_bps', models.PositiveSmallIntegerField()),
                ('applies_to_shipping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('country_code', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('country_code',), name='checkout_one_active_tax_policy_country'), models.CheckConstraint(condition=models.Q(('rate_bps__lte', 10000)), name='checkout_tax_rate_bounded')],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('country_code', 'province', 'city', 'code'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='checkout_zone_code_ci_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('country_code'), django.db.models.functions.text.Lower('province'), django.db.models.functions.text.Lower('city'), name='checkout_zone_scope_ci_unique'), models.CheckConstraint(condition=models.Q(('city', ''), models.Q(('province', ''), _negated=True), _connector='OR'), name='checkout_zone_city_requires_province')],
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='checkout.shippingzone'),
        ),
        migrations.CreateModel(
            name='CheckoutLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('line_total_toman', models.DecimalField(decimal_places=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_line', to='commerce.inventoryreservation')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_lines', to='catalog.productvariant')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='checkout.checkoutsession')),
            ],
            options={
                'ordering': ('variant_id', 'id'),
                'constraints': [models.UniqueConstraint(fields=('checkout', 'variant'), name='checkout_line_variant_unique'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 99)), name='checkout_line_quantity_bounded'), models.CheckConstraint(condition=models.Q(('unit_price_toman__gte', 0)), name='checkout_line_price_nonnegative'), models.CheckConstraint(condition=models.Q(('line_total_toman__gte', 0)), name='checkout_line_total_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='checkout_user_create_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'ready'))), fields=('user',), name='checkout_one_nonterminal_per_user'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_toman__gte', 0)), name='checkout_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('discount_toman__gte', 0)), name='checkout_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('discount_toman__lte', models.F('subtotal_toman'))), name='checkout_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_toman__gte', 0)), name='checkout_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('tax_toman__gte', 0)), name='checkout_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('payable_toman__gte', 0)), name='checkout_payable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_bps__lte', 10000)), name='checkout_session_tax_rate_bounded'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('payable_toman', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_toman'), '-', models.F('discount_toman')), '+', models.F('shipping_toman')), '+', models.F('tax_toman')))), name='checkout_payable_components'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='checkout_method_zone_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(('flat_rate_toman__gte', 0)), name='checkout_method_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(('free_over_toman__isnull', True), ('free_over_toman__gte', 0), _connector='OR'), name='checkout_method_free_over_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_max_days__isnull', True), ('delivery_min_days__isnull', True)), models.Q(('delivery_min_days__isnull', False), ('delivery_max_days__isnull', False), ('delivery_max_days__gte', models.F('delivery_min_days'))), _connector='OR'), name='checkout_method_delivery_range_valid'),
        ),
    ]
