# Generated by Django 5.2.17 on 2026-09-05 17:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("magazine", "Magazine"),
                            ("policy", "Policy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=180)),
                ("title", models.CharField(max_length=240)),
                ("excerpt", models.TextField(blank=True)),
                ("direct_answer", models.TextField(blank=True)),
                ("audience_boundary", models.TextField(blank=True)),
                ("article_type", models.CharField(blank=True, max_length=40)),
                ("author_name", models.CharField(default="تحریریه VISIO", max_length=180)),
                (
                    "author_kind",
                    models.CharField(
                        choices=[("organization", "Organization"), ("person", "Person")],
                        default="organization",
                        max_length=16,
                    ),
                ),
                ("reviewer_name", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("review_due_at", models.DateField(blank=True, null=True)),
                ("body", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("media", models.JSONField(blank=True, default=dict)),
                ("related_slugs", models.JSONField(blank=True, default=list)),
                ("seo_title", models.CharField(blank=True, max_length=240)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("search_text", models.TextField(blank=True, default="", editable=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "-published_at", "title", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "kind", "published_at", "sort_order"],
                        name="content_public_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "slug"), name="content_kind_slug_uq"),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "published"), _negated=True),
                            ("published_at__isnull", False),
                            _connector="OR",
                        ),
                        name="content_publish_time",
                    ),
                ],
            },
        ),
    ]
