# Generated by Django 5.2.17 on 2026-09-06 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", editable=False, max_length=32, unique=True),
                ),
                ("business_name", models.CharField(blank=True, max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=220)),
                ("registration_number", models.CharField(blank=True, max_length=80)),
                ("tax_identity", models.CharField(blank=True, max_length=80)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                ("business_hours", models.TextField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=list)),
                ("trust_marks", models.JSONField(blank=True, default=list)),
                ("payment_providers", models.JSONField(blank=True, default=list)),
                ("footer_tagline", models.CharField(blank=True, max_length=220)),
                ("footer_description", models.CharField(blank=True, max_length=400)),
                ("default_seo_title", models.CharField(blank=True, max_length=240)),
                ("default_seo_description", models.CharField(blank=True, max_length=320)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
        migrations.AlterField(
            model_name="contententry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("guide", "Guide"),
                    ("magazine", "Magazine"),
                    ("policy", "Policy"),
                    ("page", "Page"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=240)),
                ("message", models.TextField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("resolved", "Resolved"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="content_contact_status_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="HomepageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("category", "Category merchandising"),
                            ("editorial", "Editorial"),
                            ("guide", "Guide"),
                            ("detail", "Detail study"),
                            ("featured", "Featured collection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=160)),
                ("title", models.CharField(max_length=240)),
                ("body", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, upload_to="site/home/")),
                ("image_alt", models.CharField(blank=True, max_length=240)),
                ("target_path", models.CharField(blank=True, max_length=300)),
                ("target_label", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "sort_order"], name="content_home_public_idx"
                    )
                ],
            },
        ),
    ]
