# Generated by Django 5.2.17 on 2026-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("requesting", "pending", "verifying", "verified"))
                ),
                fields=("order",),
                name="payments_one_active_attempt_per_order",
            ),
        ),
    ]
