# Generated by Django 5.2.17 on 2026-09-03 17:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("on_hand", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_record",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("variant_id",),
            },
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="commerce.variantinventory",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["inventory", "status", "expires_at"], name="commerce_res_active_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="commerce_res_quantity_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VariantPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount_toman", models.DecimalField(decimal_places=0, max_digits=18)),
                (
                    "compare_at_toman",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_record",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("variant_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_toman__gte", 0)),
                        name="commerce_price_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("compare_at_toman__isnull", True),
                            ("compare_at_toman__gt", models.F("amount_toman")),
                            _connector="OR",
                        ),
                        name="commerce_compare_at_gt_amount",
                    ),
                ],
            },
        ),
    ]
