# Generated by Django 5.2.17 on 2026-09-05 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'audit chain state',
                'verbose_name_plural': 'audit chain state',
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=16)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'permissions': [('dispatch_notificationoutbox', 'Can dispatch notification outbox entries')],
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='ops_notify_ready_idx'), models.Index(fields=['event_type', 'created_at'], name='ops_notify_event_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', False), _connector='OR'), name='ops_notify_sent_has_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('actor_email_snapshot', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence',),
                'permissions': [('verify_audit_chain', 'Can verify the operational audit chain')],
                'indexes': [models.Index(fields=['object_type', 'object_id', 'sequence'], name='ops_audit_object_idx'), models.Index(fields=['action', 'sequence'], name='ops_audit_action_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='ops_audit_sequence_positive'), models.CheckConstraint(condition=models.Q(('event_hash', ''), _negated=True), name='ops_audit_hash_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='operations.notificationoutbox')),
            ],
            options={
                'ordering': ('notification_id', 'attempt_no'),
                'constraints': [models.UniqueConstraint(fields=('notification', 'attempt_no'), name='ops_notify_attempt_unique'), models.CheckConstraint(condition=models.Q(('attempt_no__gt', 0)), name='ops_notify_attempt_positive')],
            },
        ),
    ]
