# Generated by Django 5.2.17 on 2026-09-03 16:34

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(allow_unicode=True, max_length=160, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(allow_unicode=True, max_length=160, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ("name", models.CharField(max_length=220)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("shape", models.CharField(blank=True, max_length=120)),
                ("material", models.CharField(blank=True, max_length=120)),
                ("color", models.CharField(blank=True, max_length=120)),
                ("lens_width_mm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bridge_width_mm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("temple_length_mm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("frame_width_mm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("limited", "Limited"),
                            ("editorial", "Editorial"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("verified", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(allow_unicode=True, max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.productoption",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=120, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=apps.catalog.models.catalog_media_upload_to
                    ),
                ),
                ("alt", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductVariantOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_selections",
                        to="catalog.productoption",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_selections",
                        to="catalog.productoptionvalue",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_selections",
                        to="catalog.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="catalog_category_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "published_at", "sort_order"], name="catalog_prod_public_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "published"), _negated=True),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="catalog_prod_publish_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="productbadge",
            constraint=models.UniqueConstraint(
                fields=("product", "kind", "label"), name="catalog_badge_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                fields=("product", "key"), name="catalog_option_product_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productoptionvalue",
            constraint=models.UniqueConstraint(
                fields=("option", "value"), name="catalog_opt_value_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                condition=models.Q(("sku__isnull", False), models.Q(("sku", ""), _negated=True)),
                name="catalog_variant_sku_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("product",),
                name="catalog_one_default_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("product", "position"),
                name="catalog_product_media_pos_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("variant", "position"),
                name="catalog_variant_media_pos_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariantoption",
            constraint=models.UniqueConstraint(
                fields=("variant", "option"), name="catalog_variant_option_uq"
            ),
        ),
    ]
